change

diff --git a/traefik/Dockerfile b/traefik/Dockerfile
--- a/traefik/Dockerfile
+++ b/traefik/Dockerfile
@@ -1,14 +1,13 @@
 # syntax=docker/dockerfile:1
 FROM playn/alpine
-# ARG version=2.4.9
-RUN apk --no-cache add ca-certificates; \
-    apkArch="$(apk --print-arch)"; \
-    case "$apkArch" in \
-        armhf) arch='armv6' ;; \
-        aarch64) arch='arm64' ;; \
-        x86_64) arch='amd64' ;; \
-        *) echo >&2 "error: unsupported architecture: $apkArch"; exit 1 ;; \
-    esac; \
+RUN apk add --no-cache --no-progress ca-certificates; \
+    # apkArch="$(apk --print-arch)"; \
+    # case "$apkArch" in \
+    #     armhf) arch='armv6' ;; \
+    #     aarch64) arch='arm64' ;; \
+    #     x86_64) arch='amd64' ;; \
+    #     *) echo >&2 "error: unsupported architecture: $apkArch"; exit 1 ;; \
+    # esac; \
     export version=$(wget -qO- https://api.github.com/repos/containous/traefik/releases/latest | grep '"tag_name":' | head -n 1 | sed -E 's/.*"([^"]+)".*/\1/'); \
     wget --quiet -O /tmp/traefik.tar.gz "https://github.com/containous/traefik/releases/download/${version}/traefik_${version}_linux_$arch.tar.gz"; \
     tar xzvf /tmp/traefik.tar.gz -C /usr/local/bin traefik; \
@@ -19,11 +18,3 @@ COPY entrypoint.sh /
 EXPOSE 80
 ENTRYPOINT [ "/entrypoint.sh" ]
 CMD ["traefik"]
-
-# Metadata
-# LABEL org.opencontainers.image.vendor="Containous" \
-#     org.opencontainers.image.url="https://traefik.io" \
-#     org.opencontainers.image.title="Traefik" \
-#     org.opencontainers.image.description="A modern reverse-proxy" \
-#     org.opencontainers.image.version="v${version}" \
-#     org.opencontainers.image.documentation="https://docs.traefik.io"
